# http://spdx.org/licenses/GPL-2.0+

# build U-Boot on Travis CI - https://travis-ci.org/

language: c

install:
 - sudo apt-get update -qq
 - sudo apt-get upgrade -qq
 - sudo apt-get install -qq cppcheck sloccount device-tree-compiler gcc-arm-linux-gnueabi

script:
 - export BUILD_NCPUS="`grep processor /proc/cpuinfo | wc -l`"
 - echo "BUILD on" $BUILD_NCPUS "cpu's"
 - export CROSS_COMPILE=arm-linux-gnueabi-
 - BUILD_DIR=build ./MAKEALL --arch arm
 - rm -rf build
# QA:
 - cppcheck --force --quiet .
# TODO: room of improvement
 - grep -r TODO *
# FIXME: kind of a bug?
 - grep -r FIXME *
# HACK: release with this?
 - grep -r HACK *
# STATS:
 - sloccount .
notifications:
  email: false
