#
# Makefile for siemens IOT2050 board
# (C) Copyright 2018 Siemens AG
#   Le Jin <le.jin@siemens.com>
#
# Based on:
# U-Boot file: board/ti/am65x/Makefile
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= board.o
obj-${CONFIG_IOT2050_I2C_BOARD_DETECT} += board_detect.o
